//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_serwer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia_miedzybankowa
    {
        public int id_transakcji { get; set; }
        public decimal kwota { get; set; }
        public System.DateTime data { get; set; }
        public int kierunek_transakcji { get; set; }
        public int id_rachunku { get; set; }
        public string nr_rachunku_obcego { get; set; }
        public int status { get; set; }
        public string tytul { get; set; }
        public string nazwa_odbiorcy { get; set; }
        public string adres_odbiorcy { get; set; }
    
        public virtual Rachunki Rachunki { get; set; }
        public virtual Historia_status Historia_status { get; set; }
    }
}
