//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_serwer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rachunki_obce
    {
        public int id_rachunku { get; set; }
        public string numer { get; set; }
        public decimal dostepne_srodki { get; set; }
    }
}
