//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_serwer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rachunki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rachunki()
        {
            this.Blokady = new HashSet<Blokady>();
            this.Historia_miedzybankowa = new HashSet<Historia_miedzybankowa>();
            this.Przelew_cykliczny = new HashSet<Przelew_cykliczny>();
            this.Historia_wewnatrzbankowa = new HashSet<Historia_wewnatrzbankowa>();
            this.Historia_wewnatrzbankowa1 = new HashSet<Historia_wewnatrzbankowa>();
        }
    
        public int id_rachunku { get; set; }
        public int id_klienta { get; set; }
        public string nr_rachunku { get; set; }
        public int rodzaj_rachunku { get; set; }
        public decimal dostepne_srodki { get; set; }
        public bool blokada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blokady> Blokady { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historia_miedzybankowa> Historia_miedzybankowa { get; set; }
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przelew_cykliczny> Przelew_cykliczny { get; set; }
        public virtual Rachunki_rodzaj Rachunki_rodzaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historia_wewnatrzbankowa> Historia_wewnatrzbankowa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historia_wewnatrzbankowa> Historia_wewnatrzbankowa1 { get; set; }
    }
}
