//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przelew_cykliczny
    {
        public int id_przelewu_cyklicznego { get; set; }
        public int id_rachunku_nadawcy { get; set; }
        public int nr_rachunku_odbiorcy { get; set; }
        public decimal kwota { get; set; }
        public string tytuł { get; set; }
        public System.DateTime data_pierwszego_wykonania { get; set; }
        public int Czestotliwosc_dni { get; set; }
        public System.DateTime data_ostatniego_wykonania { get; set; }
    
        public virtual Rachunki Rachunki { get; set; }
    }
}
